### ISSUE TITLE
Crash - long press on link in article 

### ISSUE THREAD

**Issue by nayfield** [nayfield/GrazeTen#8]
Seems same error as the other long press problem 

android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java:952)
at android.app.ContextImpl.startActivity(ContextImpl.java:928)
at

**Comment by nayfield** [comment]
Pull #11 adds activity contexts to the startActivity() calls.  Will be in next release

**Comment by nayfield** [comment]
Closed in release 3.1.3
